import { lstat, readFile, readdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';

const CONTROL_FILES = new Set(['_headers', '_redirects', '.assetsignore']);
const CONTENT_TYPES = {
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.md': 'text/markdown; charset=utf-8',
  '.txt': 'text/plain; charset=utf-8',
  '.xml': 'application/xml; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.gif': 'image/gif',
  '.webp': 'image/webp',
  '.ico': 'image/x-icon',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
};

export async function collectPublicAssets(directory) {
  const root = path.resolve(directory);
  const rootStat = await lstat(root);
  if (!rootStat.isDirectory() || rootStat.isSymbolicLink()) throw new Error('Public assets must be a regular directory');
  const assets = {};
  async function visit(relative = '') {
    const names = (await readdir(path.join(root, relative))).sort();
    for (const name of names) {
      if (!relative && CONTROL_FILES.has(name)) continue;
      const filename = path.join(relative, name);
      const absolute = path.join(root, filename);
      const stat = await lstat(absolute);
      if (stat.isSymbolicLink()) throw new Error('Public assets must not contain symbolic links: ' + filename);
      if (stat.isDirectory()) {
        await visit(filename);
      } else if (stat.isFile()) {
        const bytes = await readFile(absolute);
        const pathname = '/' + filename.split(path.sep).map(encodeURIComponent).join('/');
        assets[pathname] = {
          body: bytes.toString('base64'),
          size: bytes.length,
          contentType: CONTENT_TYPES[path.extname(name).toLowerCase()] ?? 'application/octet-stream',
          etag: '"sha256-' + createHash('sha256').update(bytes).digest('hex') + '"',
        };
      } else {
        throw new Error('Public assets must be regular files: ' + filename);
      }
    }
  }
  await visit();
  if (!assets['/index.html']) throw new Error('Public assets must include index.html');
  return assets;
}

// This function is copied into the deployed ESM bundle. Keep it self-contained
// and use Web APIs rather than filesystem access or Node.js runtime bindings.
export function createEmbeddedAssets(assets) {
  const error = (request, status, message, extra = {}) => new Response(request.method === 'HEAD' ? null : message + '\n', {
    status,
    headers: { 'Content-Type': 'text/plain; charset=utf-8', 'Cache-Control': 'no-store', 'X-Content-Type-Options': 'nosniff', ...extra },
  });
  return {
    async fetch(request) {
      const pathname = new URL(request.url).pathname;
      const assetPath = pathname === '/' ? '/index.html' : pathname;
      // Exact manifest lookup is the only asset access. Encoded slashes and
      // traversal-looking paths cannot trigger a filesystem read at runtime.
      if (!Object.prototype.hasOwnProperty.call(assets, assetPath)) return error(request, 404, 'Not found');
      if (!['GET', 'HEAD'].includes(request.method)) return error(request, 405, 'Method not allowed', { Allow: 'GET, HEAD' });
      const asset = assets[assetPath];
      const headers = new Headers({
        'Content-Type': asset.contentType,
        'Cache-Control': 'public, max-age=0, must-revalidate',
        ETag: asset.etag,
        Vary: 'Accept-Encoding',
        'X-Content-Type-Options': 'nosniff',
      });
      const matches = request.headers.get('If-None-Match')?.split(',').some(value => {
        const candidate = value.trim();
        return candidate === '*' || candidate.replace(/^W\//, '') === asset.etag;
      });
      if (matches) return new Response(null, { status: 304, headers });
      headers.set('Content-Length', String(asset.size));
      const body = request.method === 'HEAD' ? null : Uint8Array.from(atob(asset.body), character => character.charCodeAt(0));
      return new Response(body, { headers });
    },
  };
}

export function buildWorkerBundle(source, assets) {
  // worker.js is a dependency-free ESM module. Retain its named exports and
  // route logic, and wrap its single default object with the embedded binding.
  const defaults = source.match(/^export default \{/gm) ?? [];
  if (defaults.length !== 1) throw new Error('Expected one default Worker object in worker.js');
  const worker = source.replace(/^export default \{/m, 'const portfolioWorker = {');
  return [
    '// Generated by scripts/build-site.mjs. Edit worker.js and public source files.',
    createEmbeddedAssets.toString(),
    'const embeddedPortfolioAssets = createEmbeddedAssets(' + JSON.stringify(assets) + ');',
    worker,
    'export default {',
    '  fetch(request, env, ctx) {',
    '    return portfolioWorker.fetch(request, { ...env, ASSETS: embeddedPortfolioAssets }, ctx);',
    '  },',
    '};',
    '',
  ].join('\n');
}
